Don't compute iOS shadows on Android and other small changes
alekhurst/react-native-elevated-view pull request #3
Opened 2017-02-22 21:09 UTC by JReinhold

I've reordered the component, so the iOS shadows are completely ignored if the it is running on Android.
I've also changed a few `let` to `const`.
I also noticed that the `shadowColor` gets removed as soon as the code enters the switch-block, this is now fixed. As 'black' is the default color this shouldn't change anything at all, just to ensure consistency.

(This is my first ever contribution to an open-source repo, so please speak up if I've done something wrong)

2017-03-02 00:56 UTC, alekhurst requested changes
Awesome! Thanks for the PR. Couple small requests.

2017-03-02 00:56 UTC, alekhurst commented on index.js
> +      return (<View elevation={elevation} style={style} {...otherProps}>
Can the style here look like:

```
return (
  <View elevation={elevation} style={style} {...otherProps}>
    {this.props.children}
  </View>
)
```

2017-03-02 00:56 UTC, alekhurst commented on index.js
> +    return (<View style={[iosShadowElevation, style]} {...otherProps}>
Same as prev comment

2017-03-05 11:24 UTC, JReinhold commented
that's a good idea, especially for readabilty.
I've also added proptype-validation for the elevation prop in the last commit.

2017-03-05 16:51 UTC, merged

2017-03-05 16:51 UTC, alekhurst commented
Looks fantastic, just merged!