calculate iOS shadows instead of static assignments
alekhurst/react-native-elevated-view pull request #5
Opened 2017-05-09 21:19 UTC by JReinhold

Fixes #4 

After a lot of trial and error and calculation, I've refactored the iOS shadow elevations to using a simple linear algorithm instead of static switch-statements.
This enables the use of an arbitrary `elevation` number instead of just 0-5.

A comparison between iOS and Android shadows resulting from the algorithm can be seen below.

It supports any elevation, however it is only tested **up to 24**, so anything exceeding that is not guaranteed to look the same across iOS and Android.
![elevationcomparison](https://cloud.githubusercontent.com/assets/5678122/25873107/6d129920-350d-11e7-8772-52234227f7c7.png)

2017-05-09 21:58 UTC, alekhurst commented
I'm open to having an algorithm determine the iOS elevation styles, but I think it needs a bit more tweaking. I have not tested on device yet, but in the screenshots the iOS version the shadows are a bit lighter than on the android version. 

If you're on mac, you can use Digital Color Meter to view the hex code at each pixel at the given distance away from the material.

2017-05-09 22:02 UTC, alekhurst requested changes

2017-05-09 22:02 UTC, alekhurst commented on index.js
> +		return (
let's use spaces instead of tabs

2017-05-11 22:08 UTC, JReinhold commented
I've tweaked the calculations using the Digital Color Meter, and having two emulators side by side to each other. I think the shadows are very similar now, I can't imagine getting any closer.

![comparev2](https://cloud.githubusercontent.com/assets/5678122/25974040/1c48b0ba-36a7-11e7-9da4-2874aa8313bb.jpg)

@alekhurst thoughts?

2017-05-12 02:20 UTC, alekhurst commented
I'm tentative, as the shadow is drastically different for `elevation: 5` which we officially support. It looks like the values for Google's material design elevation shadows don't follow a linear equation. 

Which ios/android devices were you measuring these with, and did they have similar resolutions?

2017-05-12 08:01 UTC, JReinhold commented
I get your point.

I haven't thought about the device's resolution having an impact, so I switched to using an iPhone 6 Plus and a Nexus 5X, which both operate at 1080x1920, and tweaked the calculations based on that.

![comparev3](https://cloud.githubusercontent.com/assets/5678122/25988846/f6910202-36f9-11e7-850e-0b5f48a514a7.jpg)

2017-05-20 19:33 UTC, alekhurst submitted a review, later dismissed
Sweet man, this looks great! Just one small nit

2017-05-20 19:33 UTC, alekhurst commented on index.js
> +    //Return default View if elevation is 0
Let's put this one below the `(Platform.OS === 'android')`, so it only effects iOS.

Also one nit: don't think we need the comment

2017-05-20 19:40 UTC, alekhurst commented
Also, it might be good to update the README:
* screenshots  (let's use the same light grey background with white squares, only need to show elevation 1-5). 
* officially support elevation values 0-24

2017-05-27 20:22 UTC, alekhurst commented on README.md
> +- **`elevation`** _(Integer)_ - Must be 0 or above, but anything higher than 24 is not officially supported.* The elevation you would like the elevated view to appear at.
nit: lets just say 

Must be between 0 and 24. The elevation you would like the elevated view to appear at.

2017-05-29 18:36 UTC, JReinhold commented on README.md
> +- **`elevation`** _(Integer)_ - Must be 0 or above, but anything higher than 24 is not officially supported.* The elevation you would like the elevated view to appear at.
done.

2017-05-29 18:37 UTC, alekhurst approved these changes
Sweet, go ahead and merge this puppy! I will make sure to do the npm release

2017-05-29 18:42 UTC, JReinhold commented
perfect, good job! oh, and by the way, I don't have write access to this repo, you are the one that has to merge it. ;)

2017-05-29 19:56 UTC, merged